SITE-12 Try Orchard! theme development
Lombiq/TryOrchard.net-Theme pull request #1
Opened 2019-01-21 16:04 UTC by I3undy

2019-01-23 15:30 UTC, Piedone requested changes

2019-01-23 15:30 UTC, Piedone commented on Styles/_mixins.scss
> +        padding: 0.25rem 9999rem;
Mik ezek a sokkilencek?

2019-01-23 15:30 UTC, Piedone commented on Theme.txt
> +Website: https://tryorchard.net
Dat gud!

2019-01-23 15:30 UTC, Piedone commented on TryOrchard.Theme.csproj
> +    <Content Include="Images\Favicons\android-icon-144x144.png" />
Ezek nem a company design repóban lévő aktuális logóból készültek, hanem egy korábbi verzióból. Továbbá bennmaradt az Images\favicon.ico is az Images\Favicons\favicon.ico mellett.

2019-01-23 15:31 UTC, I3undy commented on Styles/_mixins.scss
> +        padding: 0.25rem 9999rem;
https://css-tricks.com/full-browser-width-bars/

2019-01-23 15:34 UTC, I3undy commented on TryOrchard.Theme.csproj
> +    <Content Include="Images\Favicons\android-icon-144x144.png" />
Reménykedtem, hogy a logo/faviconnak dedikált issue branch-ben lévő favicon jó. Cserélem.

2019-01-23 15:37 UTC, Piedone commented on Styles/_mixins.scss
> +        padding: 0.25rem 9999rem;
Mivel az egy nagyon hosszú blogpost és még a scrollbar és custom, ezért elhiszem.

2019-01-23 17:25 UTC, Piedone requested changes

2019-01-23 17:25 UTC, Piedone commented on Views/Metas.liquid
> +<link rel="image/png" sizes="36x36" href="{{ faviconUrl }}android-chrome-36x36.png" />
Ezek az URL-ek nem fognak localban (local fájlokkal a témában), stagingben és prodban (remote fájlokkal blob storage-ben) egyaránt működni. Ahhoz a SetLink, SetMeta tageket kell használni, ahogy amúgy is csinálnád, lásd a Readme-t: https://github.com/Lombiq/Orchard-Liquid-Markup Alternatíva a Href tag használata, talán ez az egyszerűbb, így:

```
{% capture faviconBaseUrl %}{% Href "~/Themes/MyTheme/Images/Favicons/" %}{% endcapture %}

<link rel="shortcut icon" type="image/x-icon" href="{{ faviconBaseUrl }}favicon.ico" />
...
```

2019-01-24 01:03 UTC, Piedone approved these changes

2019-01-24 01:07 UTC, merged